language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: NeoAcheron
  skip_cleanup: true
  password:
    secure: Znp6wiYWcfjmIWl3Gsq+dqGLLNp3aUVDu2QTVqX5gJ9zc1MVPZE5mpw0Wfl9AUdCmO/xj7ZZ7lbhKh66xYbuvKNwStJUrSKdUL5JsNFGRxSsfaM++1wtiwNBzsATaVjBLsXhUomWfet78qsqvwLlBAT0prthoT3FP/5N8tP0TMauh2pdc+DoFyYe/D1eiTffZjiYj44Dycb965Ys5Voqu55hSE8Tiy1vKwT6wxiBvDjBSeNafpcyoLK0kDLEQomX57u7Z4T4OWPvcmIpS/U60iJ7WT4U+HxjwgvGsROPZ5vlD9sh+SZk+6GMb5nxo8jlp9RZz6C840TR7PGLskO+MvoFQuSdLEBcnnZOu9SxdYKO04LfqKBskM0n8TCDuGhLSTupS7ReaGOn5CeJmmE5qBpUm+K8Juz38zh7x0bF7rzmonUuNvSN/nY5lyg7yl457P2eeQCN/fhDEhetgp7jC6BiNJblq28DpUKRuRGgu1XOrTGk8Mdw8KXwO2Z3tE7Xi4Xz1vLv8zYs1NURJeLR3bDqfeyK5ALQbPxLhq+wIyGWzw4wuziNcaneJN6A3EUzBAu2I+jcKX/b/eW1PdBPtAxWs3r06axpCIa3Je1cnpLskqJsUar+Jw2zI82i1pM813z3/LoXdeHc10z7sJ4tLpWn49rIf/LnetYs23D3qJc=
